//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Northwind.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerDemographicEntity
    {
        public CustomerDemographicEntity()
        {
            this.Customers = new HashSet<CustomerEntity>();
        }
    
        public string CustomerTypeID { get; set; }
        public string CustomerDesc { get; set; }
    
        public virtual ICollection<CustomerEntity> Customers { get; set; }
    }
}
