//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Northwind.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class TerritoryEntity
    {
        public TerritoryEntity()
        {
            this.Employees = new HashSet<EmployeeEntity>();
        }
    
        public string TerritoryID { get; set; }
        public string TerritoryDescription { get; set; }
        public int RegionID { get; set; }
    
        public virtual RegionEntity Region { get; set; }
        public virtual ICollection<EmployeeEntity> Employees { get; set; }
    }
}
